CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR(11)
AS
BEGIN
	DECLARE @SCRIPT NVARCHAR(MAX)
	DECLARE @CAMPOS NVARCHAR(MAX)
	
	SET @CAMPOS = '@CPF VARCHAR(11)'

	SET @SCRIPT = 
	'SELECT * FROM CLIENTES WITH(NOLOCK)
	WHERE CPF = @CPF'
			
	EXECUTE SP_EXECUTESQL @SCRIPT, @CAMPOS, @CPF
END